spring:
  application:
    name: listen-to-me

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/listen-to-me
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.listen-to-me.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
